FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json .
RUN yarn install


COPY . .
ENV NEXT_PUBLIC_BACKEND_BASE_URL=http://backend:3000
RUN yarn build

#Stage 2

FROM node:alpine AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./
COPY --from=builder /app/next.config.mjs ./

RUN yarn install --production

EXPOSE 3000

CMD ["yarn","start"]
