name: CI

on:
  push:
    branches:
      - main  
      - feature/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  
      - name: Install dependencies frontend
        run: |
          cd frontend
          yarn install 

      - name: Run linting frontend
        run: |
          cd frontend
          yarn lint  

      - name: build frontend
        run: |
          cd frontend
          docker build . -t ${{secrets.DOCKER_HUB_USERNAME}}/sample-fullstack-application-frontend

      - name: install dependencies backend
        run: |
          cd backend
          yarn install

      - name: Run linting and tests backend
        run: |
          cd backend
          yarn test  

      - name: build backend
        run: |
          cd backend
          docker build . -t ${{secrets.DOCKER_HUB_USERNAME}}/sample-fullstack-application-backend
      
      
      - name: PUSH ARTIFACTS
        run: |
          echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/sample-fullstack-application-frontend
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/sample-fullstack-application-backend
      

        
      
